### ISSUE TITLE
`ImageService` is missing `@type` for IIIF2 services

### ISSUE THREAD

**Issue by jbaiter** [IIIF-Commons/presentation-3-types#7]
The type hints for the `ImageService` type only have the `type` field specified, but as per the examples in the Presentation API 3 specification, IIIFv2 image services use `@type` instead. The field is completely missing from the `ImageService2` type as well.

```
    {
      "@id": "https://example.org/iiif2/image1/identifier",
      "@type": "ImageService2",
      "profile": "http://iiif.io/api/image/2/level2.json"
    }
```
https://iiif.io/api/presentation/3.0/#service

**Comment by stephenwf** [comment]
Ah I guess that is a bug in the types. Although the ImageService2 type does confuse me a bit. I think I assumed that either it would match the 2.1 spec and be:
```json
{
  "@context": "http://iiif.io/api/image/2/context.json",
  "@id": " ... ",
   "profile": "http://iiif.io/api/image/2/level2.json"
}
```
without a type, and a context instead. 

Or perhaps:
```json
{
  "id": "https://example.org/iiif2/image1/identifier",
  "type": "ImageService2",
  "profile": "http://iiif.io/api/image/2/level2.json"
}
```

**Comment by stephenwf** [comment]
PR: https://github.com/IIIF-Commons/presentation-3-types/pull/8 (possibly incomplete)

**Comment by stephenwf** [comment]
Closing for now
